# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - 'master'

pool: 
  vmImage: 'ubuntu-latest'

variables:
- name: 'instructor'
  value: 'Mark'

#watch for PR's
pr: 'none'

#groups sequential actions
stages:
  - stage:
    jobs:
      - job: 'build'
        steps:
          - task: SonarCloudPrepare@1
            inputs:
              SonarCloud: 'KensProject0'
              organization: 'kenstestkey'
              scannerMode: 'MSBuild'
              projectKey: '0d21e1087fa69586dbafcf2bf09d229dcb40ca12'
              projectName: 'Project0Test'
          - script: dotnet build "Project0\Project0.sln"
          - script: echo "Hey there $(instructor)!"
      - job: 'test'
        dependsOn: 'build'
        steps:
          - script: dotnet test "Project0\Project0.sln"
      - job: 'publish'
        dependsOn: 'test'
        steps:
          - script: dotnet publish "Project0\Project0.sln"

name: '$(date:yyyyMMdd)$(rev:rr)'