// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RPS_Game;

namespace RPS_Game.Migrations
{
    [DbContext(typeof(RPS_DbContext))]
    partial class RPS_DbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("RPS_Game.Game", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("P1playerId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("P2playerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("WinnerplayerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("GameId");

                    b.HasIndex("P1playerId");

                    b.HasIndex("P2playerId");

                    b.HasIndex("WinnerplayerId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("RPS_Game.Player", b =>
                {
                    b.Property<int>("playerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Losses")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Ties")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Wins")
                        .HasColumnType("INTEGER");

                    b.HasKey("playerId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("RPS_Game.Round", b =>
                {
                    b.Property<int>("RoundId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("P1Choice")
                        .HasColumnType("TEXT");

                    b.Property<string>("P2Choice")
                        .HasColumnType("TEXT");

                    b.Property<int?>("WinnnerplayerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("RoundId");

                    b.HasIndex("WinnnerplayerId");

                    b.ToTable("Rounds");
                });

            modelBuilder.Entity("RPS_Game.Game", b =>
                {
                    b.HasOne("RPS_Game.Player", "P1")
                        .WithMany()
                        .HasForeignKey("P1playerId");

                    b.HasOne("RPS_Game.Player", "P2")
                        .WithMany()
                        .HasForeignKey("P2playerId");

                    b.HasOne("RPS_Game.Player", "Winner")
                        .WithMany()
                        .HasForeignKey("WinnerplayerId");
                });

            modelBuilder.Entity("RPS_Game.Round", b =>
                {
                    b.HasOne("RPS_Game.Player", "Winnner")
                        .WithMany()
                        .HasForeignKey("WinnnerplayerId");
                });
#pragma warning restore 612, 618
        }
    }
}
